//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympus.Generators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olympus.Generators.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty resource file.
        /// </summary>
        internal static string EmptyResourceFileTitle {
            get {
                return ResourceManager.GetString("EmptyResourceFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file generated without any members.
        /// </summary>
        internal static string EmptyResourceFileMessage {
            get {
                return ResourceManager.GetString("EmptyResourceFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file should have at least one member..
        /// </summary>
        internal static string EmptyResourceFileDescription {
            get {
                return ResourceManager.GetString("EmptyResourceFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key in resource file.
        /// </summary>
        internal static string InvalidResourceKeyTitle {
            get {
                return ResourceManager.GetString("InvalidResourceKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry with key '{0}' is invalid and will be ignored.
        /// </summary>
        internal static string InvalidResourceKeyMessage {
            get {
                return ResourceManager.GetString("InvalidResourceKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource keys must be valid..
        /// </summary>
        internal static string InvalidResourceKeyDescription {
            get {
                return ResourceManager.GetString("InvalidResourceKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value in resource file.
        /// </summary>
        internal static string MissingResourceValueTitle {
            get {
                return ResourceManager.GetString("MissingResourceValueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry with key '{0}' has no value and will be ignored.
        /// </summary>
        internal static string MissingResourceValueMessage {
            get {
                return ResourceManager.GetString("MissingResourceValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource keys must be valid..
        /// </summary>
        internal static string MissingResourceValueDescription {
            get {
                return ResourceManager.GetString("MissingResourceValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key in resource file.
        /// </summary>
        internal static string DuplicateResourceKeyTitle {
            get {
                return ResourceManager.GetString("DuplicateResourceKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry with key '{0}' is duplicated and will be ignored.
        /// </summary>
        internal static string DuplicateResourceKeyMessage {
            get {
                return ResourceManager.GetString("DuplicateResourceKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource keys should not be duplicates..
        /// </summary>
        internal static string DuplicateResourceKeyDescription {
            get {
                return ResourceManager.GetString("DuplicateResourceKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing translation for specific key.
        /// </summary>
        internal static string MissingResourceTranslationTitle {
            get {
                return ResourceManager.GetString("MissingResourceTranslationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry with key '{0}' is missing a translation for {1} ({2}).
        /// </summary>
        internal static string MissingResourceTranslationMessage {
            get {
                return ResourceManager.GetString("MissingResourceTranslationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource entries must have translations for all supported languages..
        /// </summary>
        internal static string MissingResourceTranslationDescription {
            get {
                return ResourceManager.GetString("MissingResourceTranslationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission identifier.
        /// </summary>
        internal static string InvalidPermissionIdentifierTitle {
            get {
                return ResourceManager.GetString("InvalidPermissionIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission identifier for key '{0}' must be a valid integer.
        /// </summary>
        internal static string InvalidPermissionIdentifierMessage {
            get {
                return ResourceManager.GetString("InvalidPermissionIdentifierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission identifier must be a valid integer..
        /// </summary>
        internal static string InvalidPermissionIdentifierDescription {
            get {
                return ResourceManager.GetString("InvalidPermissionIdentifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate permission identifier.
        /// </summary>
        internal static string DuplicatePermissionIdentifierTitle {
            get {
                return ResourceManager.GetString("DuplicatePermissionIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission identifier for key '{0}' is already in use.
        /// </summary>
        internal static string DuplicatePermissionIdentifierMessage {
            get {
                return ResourceManager.GetString("DuplicatePermissionIdentifierMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission identifier must be exclusive..
        /// </summary>
        internal static string DuplicatePermissionIdentifierDescription {
            get {
                return ResourceManager.GetString("DuplicatePermissionIdentifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission key.
        /// </summary>
        internal static string InvalidPermissionKeyTitle {
            get {
                return ResourceManager.GetString("InvalidPermissionKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The permission key '{0}' must follow the format 'Module.Feature.Action'.
        /// </summary>
        internal static string InvalidPermissionKeyMessage {
            get {
                return ResourceManager.GetString("InvalidPermissionKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission identifier must follow the format 'Module.Feature.Action'..
        /// </summary>
        internal static string InvalidPermissionKeyDescription {
            get {
                return ResourceManager.GetString("InvalidPermissionKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid route key.
        /// </summary>
        internal static string InvalidRouteKeyTitle {
            get {
                return ResourceManager.GetString("InvalidRouteKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route key '{0}' must follow the format 'Module.Segments'.
        /// </summary>
        internal static string InvalidRouteKeyMessage {
            get {
                return ResourceManager.GetString("InvalidRouteKeyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route identifier must follow the format 'Module.Segments'..
        /// </summary>
        internal static string InvalidRouteKeyDescription {
            get {
                return ResourceManager.GetString("InvalidRouteKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service lifecycle violation.
        /// </summary>
        internal static string ServiceLifecycleTitle {
            get {
                return ResourceManager.GetString("ServiceLifecycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type '{0}' implements conflicting service lifecycles: {1}.
        /// </summary>
        internal static string ServiceLifecycleMessage {
            get {
                return ResourceManager.GetString("ServiceLifecycleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that a type implements only one specific service lifecycle strategy (Transient, Scoped, Singleton, Settings, or Complex) to avoid ambiguous dependency injection registration..
        /// </summary>
        internal static string ServiceLifecycleDescription {
            get {
                return ResourceManager.GetString("ServiceLifecycleDescription", resourceCulture);
            }
        }
    }
}
