//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olympus.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olympus.Analyzers.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace violation.
        /// </summary>
        internal static string OneLevelNamespaceTitle {
            get {
                return ResourceManager.GetString("OneLevelNamespaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace '{0}' does not match the folder path and depth level. It was expected to be '{1}'..
        /// </summary>
        internal static string OneLevelNamespaceMessage {
            get {
                return ResourceManager.GetString("OneLevelNamespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that the namespace corresponds to the assembly name followed by the first directory level..
        /// </summary>
        internal static string OneLevelNamespaceDescription {
            get {
                return ResourceManager.GetString("OneLevelNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix namespace.
        /// </summary>
        internal static string OneLevelNamespaceCodeFixTitle {
            get {
                return ResourceManager.GetString("OneLevelNamespaceCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block spacing violation.
        /// </summary>
        internal static string BlockSpacingTitle {
            get {
                return ResourceManager.GetString("BlockSpacingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block should start with a blank line.
        /// </summary>
        internal static string BlockSpacingMessageAfterOpen {
            get {
                return ResourceManager.GetString("BlockSpacingMessageAfterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block should end with a blank line.
        /// </summary>
        internal static string BlockSpacingMessageBeforeClose {
            get {
                return ResourceManager.GetString("BlockSpacingMessageBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces the insertion of a blank line at the beginning and end of blocks..
        /// </summary>
        internal static string BlockSpacingDescription {
            get {
                return ResourceManager.GetString("BlockSpacingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer spacing violation.
        /// </summary>
        internal static string InitializerSpacingTitle {
            get {
                return ResourceManager.GetString("InitializerSpacingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer must not start with a blank line.
        /// </summary>
        internal static string InitializerSpacingMessageRemoveAfterOpen {
            get {
                return ResourceManager.GetString("InitializerSpacingMessageRemoveAfterOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be no blank lines between items.
        /// </summary>
        internal static string InitializerSpacingMessageRemoveBetweenItems {
            get {
                return ResourceManager.GetString("InitializerSpacingMessageRemoveBetweenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializer must not end with a blank line.
        /// </summary>
        internal static string InitializerSpacingMessageRemoveBeforeClose {
            get {
                return ResourceManager.GetString("InitializerSpacingMessageRemoveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that initializers do not begin or end with blank lines..
        /// </summary>
        internal static string InitializerSpacingDescription {
            get {
                return ResourceManager.GetString("InitializerSpacingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line.
        /// </summary>
        internal static string BlockSpacingCodeFixTitle {
            get {
                return ResourceManager.GetString("BlockSpacingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank line.
        /// </summary>
        internal static string InitializerSpacingCodeFixTitle {
            get {
                return ResourceManager.GetString("InitializerSpacingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return statement spacing violation.
        /// </summary>
        internal static string ReturnSpacingTitle {
            get {
                return ResourceManager.GetString("ReturnSpacingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return statement must be preceded by a blank line.
        /// </summary>
        internal static string ReturnSpacingMessage {
            get {
                return ResourceManager.GetString("ReturnSpacingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces the insertion of a blank line before the return statement, unless it is on the same line as the previous statement or is the first statement in a block..
        /// </summary>
        internal static string ReturnSpacingDescription {
            get {
                return ResourceManager.GetString("ReturnSpacingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert a blank line before the return statement.
        /// </summary>
        internal static string ReturnSpacingCodeFixTitle {
            get {
                return ResourceManager.GetString("ReturnSpacingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda parameter naming violation.
        /// </summary>
        internal static string LambdaParameterNamingTitle {
            get {
                return ResourceManager.GetString("LambdaParameterNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter '{0}' should be renamed to '{1}' to match its type.
        /// </summary>
        internal static string LambdaParameterNamingMessage {
            get {
                return ResourceManager.GetString("LambdaParameterNamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that lambda parameters use meaningful names derived from their type instead of single letters..
        /// </summary>
        internal static string LambdaParameterNamingDescription {
            get {
                return ResourceManager.GetString("LambdaParameterNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to '{0}'.
        /// </summary>
        internal static string LambdaParameterNamingCodeFixTitle {
            get {
                return ResourceManager.GetString("LambdaParameterNamingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression can be static.
        /// </summary>
        internal static string StaticLambdaTitle {
            get {
                return ResourceManager.GetString("StaticLambdaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This expression does not capture any state and can be marked static.
        /// </summary>
        internal static string StaticLambdaMessage {
            get {
                return ResourceManager.GetString("StaticLambdaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces the use of the static modifier on expressions that do not capture state..
        /// </summary>
        internal static string StaticLambdaDescription {
            get {
                return ResourceManager.GetString("StaticLambdaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make expression static.
        /// </summary>
        internal static string StaticLambdaCodeFixTitle {
            get {
                return ResourceManager.GetString("StaticLambdaCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix naming violation.
        /// </summary>
        internal static string SuffixNamingTitle {
            get {
                return ResourceManager.GetString("SuffixNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type '{0}' should end with the suffix '{1}'.
        /// </summary>
        internal static string SuffixNamingMessage {
            get {
                return ResourceManager.GetString("SuffixNamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that types inheriting from classes or implementing interfaces share the same suffix..
        /// </summary>
        internal static string SuffixNamingDescription {
            get {
                return ResourceManager.GetString("SuffixNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to '{0}'.
        /// </summary>
        internal static string SuffixNamingCodeFixTitle {
            get {
                return ResourceManager.GetString("SuffixNamingCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File naming violation.
        /// </summary>
        internal static string FileNamingTitle {
            get {
                return ResourceManager.GetString("FileNamingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name '{0}' does not match the expected type name '{1}'.
        /// </summary>
        internal static string FileNamingMessage {
            get {
                return ResourceManager.GetString("FileNamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforces that the file name matches the declared type name (or the first type name if multiple are present)..
        /// </summary>
        internal static string FileNamingDescription {
            get {
                return ResourceManager.GetString("FileNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file to '{0}'.
        /// </summary>
        internal static string FileNamingCodeFixTitle {
            get {
                return ResourceManager.GetString("FileNamingCodeFixTitle", resourceCulture);
            }
        }
    }
}
