namespace Olympus.Generators;

[Generator]
public sealed class HostInfoGenerator : IIncrementalGenerator {

	private const string IAppModuleInfoInterface = "Olympus.Core.Modules.IAppModuleInfo";

	private const string IAppModuleLayerInterface = "Olympus.Core.Modules.IAppModuleLayer";

	private static bool TryGenerateSource(Compilation compilation, AnalyzerConfigOptions globalOptions, [NotNullWhen(true)] out string? sourceCode, [NotNullWhen(true)] out string? fileName, CancellationToken cancellationToken) {

		sourceCode = string.Empty;
		fileName = null;

		if (!globalOptions.TryGetString("SolutionName", out var solutionName)) return false;
		if (!globalOptions.TryGetHostInfo(out var builderType, out var hostPrefix)) return false;

		var rootNamespace = compilation.AssemblyName ?? $"{solutionName}.{hostPrefix}.Host";
		var hostInfoClassName = $"{hostPrefix}HostInfo";

		string baseClassType;
		string? specializedDIRegistration = null;

		if (hostPrefix == "Api") {

			baseClassType = "global::Olympus.Api.Hosting.ApiHostInfo";
			specializedDIRegistration = $"builder.Services.AddSingleton<{baseClassType}>(info);";

		} else if (hostPrefix == "Web") {

			baseClassType = "global::Olympus.Web.Hosting.WebHostInfo";
			specializedDIRegistration = $"builder.Services.AddSingleton<{baseClassType}>(info);";

		} else {

			baseClassType = "global::Olympus.Core.Hosting.AppHostInfo";

		}

		var constructorBody = GetConstructorBody(compilation, solutionName, hostPrefix, cancellationToken);
		var specializedConstructorBody = GetSpecializedConstructorBody(compilation, solutionName, hostPrefix, cancellationToken);
		var specializedProperties = GetSpecializedProperties(hostPrefix);

		fileName = $"{hostInfoClassName}.g.cs";

		var builder = new StringBuilder(4096);

		builder.AppendLine($$"""
            // <auto-generated/>

            #nullable enable

            using Microsoft.Extensions.DependencyInjection;

            namespace {{rootNamespace}};

            /// <summary>Auto-generated implementation of {{baseClassType}} for the {{hostPrefix}} Host.</summary>
            public sealed class {{hostInfoClassName}} : {{baseClassType}} {

                /// <inheritdoc/>
                public override global::System.Reflection.Assembly Assembly => typeof(global::{{rootNamespace}}.{{hostInfoClassName}}).Assembly;

                /// <inheritdoc/>
                public override global::System.Collections.Generic.List<global::Olympus.Core.Modules.IAppModuleInfo> ModulesInfo { get; } = [];

                /// <inheritdoc/>
                public override global::System.Collections.Generic.List<global::System.Reflection.Assembly> ModulesAssemblies { get; } = [];

            {{specializedProperties}}

                public {{hostInfoClassName}}() {

            {{constructorBody}}

            {{specializedConstructorBody}}

                }

            }

            /// <summary>Provides an extension method for registering the {{hostInfoClassName}}.</summary>
            public static class {{hostInfoClassName}}Extensions {

                /// <summary>Creates the {{hostInfoClassName}}, registers it and all its modules into the DI container.</summary>
                /// <returns>Returns the instance for immediate use.</returns>
                public static global::{{rootNamespace}}.{{hostInfoClassName}} Get{{hostPrefix}}HostInfo(this {{builderType}} builder) {

                    var info = new global::{{rootNamespace}}.{{hostInfoClassName}}();

                    // Register Host Info (Base)
                    builder.Services.AddSingleton<global::Olympus.Core.Hosting.AppHostInfo>(info);

                    // Register Host Info (Specialized)
                    {{specializedDIRegistration ?? "// Not applicable"}}

                    // Register Modules from Host Info
                    foreach (var module in info.ModulesInfo) {

                        builder.Services.AddSingleton<global::Olympus.Core.Modules.IAppModuleInfo>(module);
                        builder.Services.AddSingleton(module.GetType(), module);

                    }

                    return info;

                }

            }

            """);

		sourceCode = builder.ToString().TrimLines();

		return true;

	}

	private static string GetConstructorBody(Compilation compilation, string solutionName, string hostPrefix, CancellationToken cancellationToken) {

		var appModuleInfoSymbol = compilation.GetTypeByMetadataName(IAppModuleInfoInterface);
		var appModuleLayerSymbol = compilation.GetTypeByMetadataName(IAppModuleLayerInterface);

		var modulesCode = new StringBuilder();
		var layersCode = new StringBuilder();

		foreach (var assembly in compilation.GetSolutionAssemblies(solutionName)) {

			cancellationToken.ThrowIfCancellationRequested();

			if (assembly.Name.EndsWith(".Archend", StringComparison.OrdinalIgnoreCase)) {

				if (appModuleInfoSymbol is not null) {

					foreach (var type in assembly.GetAllTypes()) {

						if (type.IsConcreteClass() && type.Implements(appModuleInfoSymbol)) {

							modulesCode.AppendLine($"        ModulesInfo.Add(new {type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}());");

						}

					}

				}

			} else if (hostPrefix == "Api" && assembly.Name.EndsWith(".Backend", StringComparison.OrdinalIgnoreCase) || hostPrefix == "Web" && assembly.Name.EndsWith(".Frontend", StringComparison.OrdinalIgnoreCase)) {

				if (appModuleLayerSymbol is not null) {

					foreach (var type in assembly.GetAllTypes()) {

						if (type.IsConcreteClass() && type.Implements(appModuleLayerSymbol)) {

							layersCode.AppendLine($"        ModulesAssemblies.Add(typeof({type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).Assembly);");

						}

					}

				}

			}

		}

		var builder = new StringBuilder();

		if (modulesCode.Length > 0) {

			builder.AppendLine("        // Modules");
			builder.Append(modulesCode);

		}

		if (layersCode.Length > 0) {

			builder.AppendLine();
			builder.AppendLine("        // Assemblies");
			builder.Append(layersCode);

		}

		return builder.ToString().TrimEnd();

	}

	private static string GetSpecializedProperties(string hostPrefix) {

		return hostPrefix switch {
			"Api" => """
				/// <inheritdoc/>
				public override global::System.Collections.Generic.IEnumerable<global::System.Type> EndpointsTypes { get; init; }

				/// <inheritdoc/>
				public override global::System.Action<global::FastEndpoints.ReflectionCache> EndpointsReflection { get; init; }
			""",
			_ => string.Empty
		};

	}

	private static string GetSpecializedConstructorBody(Compilation compilation, string solutionName, string hostPrefix, CancellationToken cancellationToken) {

		return hostPrefix switch {
			"Api" => GetApiSpecializedBody(compilation, solutionName, cancellationToken),
			_ => string.Empty
		};

	}

	private static string GetApiSpecializedBody(Compilation compilation, string solutionName, CancellationToken cancellationToken) {

		var builderTypes = new StringBuilder();
		var builderReflection = new StringBuilder();

		foreach (var assembly in compilation.GetSolutionAssemblies(solutionName)) {

			cancellationToken.ThrowIfCancellationRequested();

			if (!(assembly.Name.EndsWith(".Backend", StringComparison.OrdinalIgnoreCase) || assembly.Name.EndsWith(".Api", StringComparison.OrdinalIgnoreCase))) continue;

			var discoveredType = assembly.GetTypeByMetadataName($"{assembly.Name}.DiscoveredTypes");

			if (discoveredType is not null) builderTypes.AppendLine($"        types = types.Concat(global::{assembly.Name}.DiscoveredTypes.All);");

			var reflectionType = assembly.GetTypeByMetadataName($"{assembly.Name}.GeneratedReflection");

			if (reflectionType is not null) {

				var methodName = $"AddFrom{assembly.Name.Replace(".", "")}";

				if (reflectionType.GetMembers(methodName).Any()) {

					builderReflection.AppendLine($"            global::{assembly.Name}.GeneratedReflection.{methodName}(cache);");

				}

			}

		}

		var builder = new StringBuilder();

		builder.AppendLine("        // Endpoints Types");
		builder.AppendLine("        var types = global::System.Linq.Enumerable.Empty<global::System.Type>();");
		builder.Append(builderTypes);
		builder.AppendLine();
		builder.AppendLine("        EndpointsTypes = types;");
		builder.AppendLine();
		builder.AppendLine("        // Endpoints Reflection");
		builder.AppendLine("        EndpointsReflection = cache => {");
		builder.Append(builderReflection);
		builder.AppendLine("        };");

		return builder.ToString().TrimEnd();

	}

	public void Initialize(IncrementalGeneratorInitializationContext context) {

		var compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

		context.RegisterSourceOutput(compilationAndOptions, static (context, source) => {

			(var compilation, var optionsProvider) = source;
			var globalOptions = optionsProvider.GlobalOptions;

			try {

				List<Diagnostic> diagnostics = [];

				if (TryGenerateSource(compilation, globalOptions, out var sourceText, out var fileName, context.CancellationToken)) {

					context.AddSource(fileName, SourceText.From(sourceText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

				}

				foreach (var diagnostic in diagnostics) {

					context.ReportDiagnostic(diagnostic);

				}

			} catch (OperationCanceledException) {

				throw;

			} catch (Exception exception) {

				var errorText = $"#error HostInfoGenerator failed: {exception.ToString().Replace("\n", " ")}";
				context.AddSource("Error_HostInfoGenerator.g.cs", SourceText.From(errorText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

			}

		});

	}

}
