namespace Olympus.Generators;

[Generator]
public sealed class ModuleLayerGenerator : IIncrementalGenerator {

	private static bool TryGenerateLayerClass(Compilation compilation, AnalyzerConfigOptions globalOptions, AppModuleLayerType layerType, out string fileName, out string sourceCode) {

		fileName = string.Empty;
		sourceCode = string.Empty;

		if (!globalOptions.TryGetString("SolutionName", out var solutionName)) solutionName = "Olympus";

		if (!globalOptions.TryGetString("RootNamespace", out var rootNamespace)) rootNamespace = compilation.AssemblyName;

		if (string.IsNullOrEmpty(rootNamespace)) return false;

		var moduleName = ExtractModuleName(rootNamespace!, solutionName!, layerType);

		if (string.IsNullOrEmpty(moduleName)) return false;

		var className = $"{moduleName}Module{layerType}Layer";
		var staticModuleClass = $"{moduleName}Module";
		var moduleBaseNamespace = GetModuleBaseNamespace(rootNamespace!, layerType);
		var archendNamespace = $"{moduleBaseNamespace}.Archend";
		var staticModuleFullName = $"global::{archendNamespace}.{staticModuleClass}";

		fileName = $"{className}.g.cs";

		var builder = new StringBuilder(2048);

		builder.AppendLine($$"""
			// <auto-generated/>

			#nullable enable

			namespace {{rootNamespace}};

			/// <summary>Represents the {{layerType}} layer of the {{moduleName}} module.</summary>
			public sealed partial class {{className}} : global::Olympus.Core.Modules.AppModuleLayer {

				/// <inheritdoc/>
			    public override string CodeName => {{staticModuleFullName}}.CodeName;

				/// <inheritdoc/>
			    public override string DisplayName => {{staticModuleFullName}}.Values.DisplayName;

				/// <inheritdoc/>
			    public override global::Olympus.Core.Modules.AppModuleLayerType LayerType => global::Olympus.Core.Modules.AppModuleLayerType.{{layerType}};

			}

			""");

		sourceCode = builder.ToString().TrimLines();

		return true;

	}

	private static string? ExtractModuleName(string rootNamespace, string solutionName, AppModuleLayerType layerType) {

		var layerSuffix = $".{layerType}";
		var nameWithoutLayer = rootNamespace;

		if (rootNamespace.EndsWith(layerSuffix, StringComparison.OrdinalIgnoreCase)) {

			nameWithoutLayer = rootNamespace[..^layerSuffix.Length];

		}

		var solutionPrefix = $"{solutionName}.";

		if (nameWithoutLayer.StartsWith(solutionPrefix, StringComparison.OrdinalIgnoreCase)) {

			return nameWithoutLayer[solutionPrefix.Length..];

		}

		return nameWithoutLayer;

	}

	private static string GetModuleBaseNamespace(string rootNamespace, AppModuleLayerType layerType) {

		var layerSuffix = $".{layerType}";

		if (rootNamespace.EndsWith(layerSuffix, StringComparison.OrdinalIgnoreCase)) {

			return rootNamespace[..^layerSuffix.Length];

		}

		return rootNamespace;

	}

	private static AppModuleLayerType GetLayerType(AnalyzerConfigOptions globalOptions) {

		if (globalOptions.TryGetValue("build_property.IsArchendLayer", out var isArchend) && string.Equals(isArchend, "true", StringComparison.OrdinalIgnoreCase)) {

			return AppModuleLayerType.Archend;

		}

		if (globalOptions.TryGetValue("build_property.IsBackendLayer", out var isBackend) && string.Equals(isBackend, "true", StringComparison.OrdinalIgnoreCase)) {

			return AppModuleLayerType.Backend;

		}

		if (globalOptions.TryGetValue("build_property.IsFrontendLayer", out var isFrontend) && string.Equals(isFrontend, "true", StringComparison.OrdinalIgnoreCase)) {

			return AppModuleLayerType.Frontend;

		}

		return AppModuleLayerType.None;

	}

	private static bool IsModulePackage(AnalyzerConfigOptions globalOptions) {

		return globalOptions.TryGetValue("build_property.IsModulePackage", out var value) && string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);

	}

	public void Initialize(IncrementalGeneratorInitializationContext context) {

		var compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

		context.RegisterSourceOutput(compilationAndOptions, static (context, source) => {

			(var compilation, var optionsProvider) = source;
			var globalOptions = optionsProvider.GlobalOptions;

			if (!IsModulePackage(globalOptions)) return;

			var layerType = GetLayerType(globalOptions);

			if (layerType == AppModuleLayerType.None) return;

			try {

				if (TryGenerateLayerClass(compilation, globalOptions, layerType, out var fileName, out var sourceCode)) {

					context.AddSource(fileName, SourceText.From(sourceCode, Encoding.UTF8, SourceHashAlgorithm.Sha256));

				}

			} catch (OperationCanceledException) {

				throw;

			} catch (Exception exception) {

				var errorText = $"#error ModuleLayerGenerator failed: {exception.ToString().Replace("\n", " ")}";
				context.AddSource("Error_ModuleLayerGenerator.g.cs", SourceText.From(errorText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

			}

		});

	}

}
