namespace Olympus.Generators;

[Generator]
public sealed class PermissionsGenerator : IIncrementalGenerator {

	private class PermissionNode(string name) {

		public string Name { get; } = name;

		public Dictionary<string, PermissionNode> Children { get; } = [];

		public List<PermissionEntry> Permissions { get; } = [];

	}

	private readonly record struct PermissionEntry(int Id, string Name, string Description, string ModuleName, string FullKey);

	private static bool TryGenerateSource(ResourceCollection resourceCollection, in List<Diagnostic> diagnostics, [NotNullWhen(true)] out string? sourceCode, CancellationToken cancellationToken) {

		var resourceInformation = resourceCollection.BaseInformation;

		if (!resourceInformation.ResourceFile.TryGetResourceDataAndValues(diagnostics, out var values, cancellationToken)) {

			sourceCode = string.Empty;

			return false;

		}

		if (values.Count == 0) {

			sourceCode = string.Empty;

			diagnostics.Add(Diagnostic.Create(BuildHelper.EmptyResourceFile, Location.Create(resourceInformation.ResourceFile.Path, default, default)));

			return false;

		}

		var rootNode = BuildPermissionsTree(values, resourceInformation.ResourceFile, diagnostics);

		if (diagnostics.Any(diag => diag.Severity == DiagnosticSeverity.Error)) {

			sourceCode = string.Empty;

			return false;

		}

		var rootNamespace = resourceInformation.ResourceSettings.Namespace;
		var className = resourceInformation.ClassName;
		var resourceName = resourceInformation.ResourceName;
		var cultureCode = BuildHelper.GetCultureCode(null);
		var singletonCode = BuildHelper.GetSingletonCode(className);
		var resourceManagerCode = BuildHelper.GetResourceManagerCode(resourceName, className, true);
		var getStringCode = BuildHelper.GetGetStringCode(true);
		var memebers = GenerateNodeMembers(rootNode, "    ");

		var builder = new StringBuilder(4096);

		builder.AppendLine($$"""
			// <auto-generated/>

			#nullable enable

			namespace {{rootNamespace}};

			/// <summary>Permissions class for '{{resourceInformation.ResourceFile.Path}}'.</summary>
			public sealed class {{className}} {

			{{singletonCode}}

			{{cultureCode}}

			{{resourceManagerCode}}

			{{getStringCode}}

			{{memebers}}

			}

			""");

		sourceCode = builder.ToString().TrimLines();

		return true;

	}

	private static PermissionNode BuildPermissionsTree(Dictionary<string, XElement> values, AdditionalText file, List<Diagnostic> diagnostics) {

		var root = new PermissionNode("Root");
		var usedIds = new HashSet<int>();

		foreach (var pair in values) {

			var key = pair.Key;
			var valueElement = pair.Value;
			var dataElement = valueElement.Parent;
			var parts = key.Split('.');

			if (parts.Length != 3) {

				diagnostics.Add(Diagnostic.Create(BuildHelper.InvalidPermissionKey, BuildHelper.GetXElementLocation(file, dataElement!, key), key));

				continue;

			}

			var commentNode = dataElement?.Element("comment");
			var commentValue = commentNode?.Value?.Trim();

			if (string.IsNullOrWhiteSpace(commentValue) || !int.TryParse(commentValue, out var id)) {

				diagnostics.Add(Diagnostic.Create(BuildHelper.InvalidPermissionIdentifier, BuildHelper.GetXElementLocation(file, dataElement!, key), key));

				continue;

			}

			if (!usedIds.Add(id)) {

				diagnostics.Add(Diagnostic.Create(BuildHelper.DuplicatePermissionIdentifier, BuildHelper.GetXElementLocation(file, dataElement!, key), key));

				continue;

			}

			var moduleName = BuildHelper.GetIdentifierFromResourceName(parts[0]);
			var featureName = BuildHelper.GetIdentifierFromResourceName(parts[1]);
			var actionName = BuildHelper.GetIdentifierFromResourceName(parts[2]);
			var description = valueElement.Value.Trim();

			if (!root.Children.TryGetValue(featureName, out var featureNode)) {

				featureNode = new PermissionNode(featureName);

				root.Children[featureName] = featureNode;

			}

			featureNode.Permissions.Add(new PermissionEntry(id, actionName, description, moduleName, key));

		}

		return root;

	}

	private static string GenerateNodeMembers(PermissionNode node, string indent) {

		var builder = new StringBuilder(4096);

		foreach (var child in node.Children.Values) {

			builder.AppendLine($"{indent}/// <summary>Permissions for {child.Name}.</summary>");
			builder.AppendLine($"{indent}public static class {child.Name} {{");
			builder.AppendLine();

			foreach (var perm in child.Permissions) {

				var docComment = BuildHelper.GetTrimmedDocComment(perm.Description);

				builder.AppendLine($"{indent}    /// <summary>{docComment} (ID: {perm.Id})</summary>");
				builder.AppendLine($"{indent}    public const int {perm.Name} = {perm.Id};");
				builder.AppendLine();

			}

			builder.AppendLine($"{indent}}}");
			builder.AppendLine();

		}

		builder.AppendLine($"{indent}/// <summary>Gets all permissions defined in this module as objects.</summary>");
		builder.AppendLine($"{indent}public global::System.Collections.Generic.IEnumerable<global::Olympus.Core.Identity.PermissionInfo> GetPermissionsInfo() {{");
		builder.AppendLine();

		foreach (var child in node.Children.Values) {

			foreach (var perm in child.Permissions) {

				builder.Append($"{indent}    yield return new global::Olympus.Core.Identity.PermissionInfo {{ ");
				builder.Append($"Value = {perm.Id}, ");
				builder.Append($"Name = \"{perm.FullKey}\", ");
				builder.Append($"Description = GetString(\"{perm.FullKey}\"), ");
				builder.Append($"Module = \"{perm.ModuleName}\", ");
				builder.Append($"Feature = \"{child.Name}\", ");
				builder.Append($"Action = \"{perm.Name}\"");
				builder.AppendLine(" };");

			}

		}

		builder.AppendLine();
		builder.AppendLine($"{indent}}}");
		builder.AppendLine();

		return builder.ToString().TrimEnd();

	}

	private static ResourceInformation[] CreateResourceInformation(AnalyzerConfigOptionsProvider optionsProvider, AdditionalText resourceFile, CompilationInformation compilationInfo) {

		var globalOptions = optionsProvider.GlobalOptions;
		var resourceOptions = optionsProvider.GetOptions(resourceFile);

		if (!(resourceOptions.GetValue("build_metadata.EmbeddedResource.ResourceType") == "Permissions")) return [];

		var rootNamespace = globalOptions.GetValue("build_property.RootNamespace") ?? compilationInfo.AssemblyName;
		var customNamespace = resourceOptions.GetValue("build_metadata.EmbeddedResource.Namespace");
		var isPublic = resourceOptions.GetBoolValue("build_metadata.EmbeddedResource.IsPublic") ?? true;
		var className = resourceOptions.GetValue("build_metadata.EmbeddedResource.ClassName");
		var resourceFileName = Path.GetFileNameWithoutExtension(resourceFile.Path);
		var resourceAccessName = className is null || string.IsNullOrEmpty(className) ? string.Join(".", rootNamespace, resourceFileName) : className;

		if (BuildHelper.SplitName(resourceFileName, out _, out var suffix)) {

			try {

				CultureInfo.GetCultureInfo(suffix);

				return [];

			} catch (CultureNotFoundException) { }

		}

		BuildHelper.SplitName(resourceAccessName, out var resourceNamespace, out var resourceClassName);

		return [
			new ResourceInformation() {
				CompilationInformation = compilationInfo,
				ResourceFile = resourceFile,
				ResourceSettings = new ResourceSettings {
					IsPublic = isPublic,
					RootNamespace = rootNamespace,
					Namespace = !string.IsNullOrEmpty(customNamespace) ? customNamespace : resourceNamespace,
					ClassName = !string.IsNullOrEmpty(className) ? className : resourceClassName,
					DefaultLang = null,
					EmitFormatMethods = false,
				},
				ResourceFileName = resourceFileName,
				ResourceName = string.Join(".", rootNamespace, resourceFileName),
				Namespace = resourceNamespace,
				ClassName = resourceClassName,
			},
		];

	}

	public void Initialize(IncrementalGeneratorInitializationContext context) {

		var resources = context.AdditionalTextsProvider.Where(static file => file.Path.EndsWith("Permissions.resx", StringComparison.OrdinalIgnoreCase));
		var compilation = context.CompilationProvider.Select(static (compilation, _) => new CompilationInformation { AssemblyName = compilation.AssemblyName });
		var resourcesToGenerate = resources.Combine(context.AnalyzerConfigOptionsProvider.Combine(compilation)).SelectMany(static (values, _) => { (var resourceFile, (var optionsProvider, var compilationInfo)) = values; return CreateResourceInformation(optionsProvider, resourceFile, compilationInfo); });

		context.RegisterSourceOutput(

			resourcesToGenerate,

			static (context, resourceInformation) => {

				try {

					List<Diagnostic> diagnostics = [];

					var collection = new ResourceCollection {
						BaseInformation = resourceInformation,
						OtherLanguages = ImmutableDictionary<CultureInfo, AdditionalText>.Empty,
						FileHintName = $"{resourceInformation.ResourceFileName}.Designer.g.cs"
					};

					if (TryGenerateSource(collection, diagnostics, out var sourceText, context.CancellationToken)) {

						context.AddSource(
							$"{resourceInformation.ResourceFileName}.Designer.g.cs",
							SourceText.From(sourceText, Encoding.UTF8, SourceHashAlgorithm.Sha256)
						);

					}

					foreach (var diagnostic in diagnostics) {

						context.ReportDiagnostic(diagnostic);

					}

				} catch (OperationCanceledException) {

					throw;

				} catch (Exception exception) {

					var errorText = $"#error PermissionsGenerator failed: {exception.ToString().Replace("\n", " ")}";
					context.AddSource($"Error_{resourceInformation.ResourceFileName}.g.cs", SourceText.From(errorText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

				}

			}

		);

	}

}
