namespace Olympus.Generators;

[Generator]
public sealed class SettingsGenerator : IIncrementalGenerator {

	public static bool TryGenerateSource(Compilation compilation, AnalyzerConfigOptions globalOptions, [NotNullWhen(true)] out string? sourceCode) {

		sourceCode = string.Empty;

		if (!globalOptions.TryGetString("SolutionName", out var solutionName)) return false;
		if (!globalOptions.TryGetHostInfo(out var builderType, out var hostPrefix)) return false;

		var rootNamespace = compilation.AssemblyName ?? $"{solutionName}.{hostPrefix}.Host";

		var builder = new StringBuilder(1024);

		builder.AppendLine($$"""
			// <auto-generated/>

			#nullable enable

			using Olympus.Core.Settings;

			namespace {{rootNamespace}};

			/// <summary>Provides an extension method for loading application settings.</summary>
			public static class SettingsRegistrator {

			    /// <summary>Configures the application configuration by loading settings from assembly, JSON files, environment variables and user secrets.</summary>
			    public static void LoadSettings(this {{builderType}} builder) {

			        builder.Configuration.LoadSettings(typeof(global::{{rootNamespace}}.SettingsRegistrator).Assembly);

			    }

			}

			""");

		sourceCode = builder.ToString().TrimLines();

		return true;

	}

	public void Initialize(IncrementalGeneratorInitializationContext context) {

		var compilationAndOptions = context.CompilationProvider.Combine(context.AnalyzerConfigOptionsProvider);

		context.RegisterSourceOutput(compilationAndOptions, static (context, source) => {

			(var compilation, var optionsProvider) = source;
			var globalOptions = optionsProvider.GlobalOptions;

			try {

				if (TryGenerateSource(compilation, globalOptions, out var sourceText)) {

					context.AddSource("SettingsRegistrator.g.cs", SourceText.From(sourceText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

				}

			} catch (OperationCanceledException) {

				throw;

			} catch (Exception exception) {

				var errorText = $"#error SettingsGenerator failed: {exception.ToString().Replace("\n", " ")}";

				context.AddSource("Error_SettingsGenerator.g.cs", SourceText.From(errorText, Encoding.UTF8, SourceHashAlgorithm.Sha256));

			}

		});

	}

}
